### PR TITLE
JERSEY-3180-OsgiRegistry_classToBundleMapping_not_threadsafe

### PR DESCRIPTION
**Pull request by engelwi**
fixed issue Jersey-3180

### CODE REVIEW

**Comment by pavelbucek** [comment]
Hi Anthony,

thanks for your contribution!

We cannot merge anything into Jersey without you signing Oracle Contributor Agreement - OCA: http://www.oracle.com/technetwork/community/oca-486395.html

Please let us know whether you plan to do that.

Best regards,
Pavel

**Comment by engelwi** [comment]
Pavel,

Just signed and mailed the OCA

Yours,
Wim Engels

**Comment by engelwi** [comment]
Pavel,

The OCA has been signed :

   - Win Engels - Jersey - GitHub engelwi

Yours,
Wim Engels

**Comment by tomdw** [comment]
@pavelbucek can this pull request proceed?

**Comment by bastijns-jeroen** [comment]
@pavelbucek any news on this one?

**Comment by pavelbucek** [comment]
merged to master branch.

Thanks for your contribution!

**Pull request closed without merging**
