### PR TITLE
JERSEY-2429: JDK8 support

### PR DESCRIPTION
**Pull request by cowwoc**
I merged a subset of https://github.com/jersey/jersey/commit/411f767d3686ee494000741ee60f24419264679c into Jersey 1.x.

This fix works for me. Please review, test, and merge.

Please note I only merged JDK8-specific changes. I ignored localization and other enhancements, which you might want to also merge.

### CODE REVIEW

**Comment by HiJon89** [comment]
Would be great if this got merged and released

**Comment by mgajdos** [comment]
@cowwoc Can you, please, create a new pull request (or edit this one if it's possible) and target the change to branch 1.18.x and not 1.18.1? I'll merge it then and cherry-pick it to master. Thanks.

**Comment by HiJon89** [comment]
Hooray!

**Comment by seratch** [comment]
Good news :smiley:

**Comment by cowwoc** [comment]
@mgajdos Try the updated PR. I couldn't test it locally because I'm blocked on JERSEY-2430 and installing JDK7 on this machine is too much of a headache.

**Comment by cowwoc** [comment]
@mgajdos Also, https://github.com/jersey/jersey-1.x/pull/12 needs your help (I'm unable to proceed).

**Comment by mgajdos** [comment]
Gili, you're still trying to merge the change into 1.18.1 branch, see:

    cowwoc  wants to merge 9 commits into jersey:1.18.1 from cowwoc:JERSEY-2429

The target branch should be changed to `jersey:1.18.x`. I am not sure but I guess you need to create a new pull request for that. Sorry, maybe I wasn't clear the first time.

**Comment by cowwoc** [comment]
@mgajdos Try https://github.com/jersey/jersey-1.x/pull/13

**Comment by mgajdos** [comment]
Merged new pull request (#13)

**Comment by cowwoc** [comment]
Good luck guys! I hope this helps.

**Comment by mgajdos** [comment]
@cowwoc Thank you for your contribution.

**Pull request closed without merging**
