### PR TITLE
JERSEY-2429: JDK 8 support

### PR DESCRIPTION
**Pull request by cowwoc**

### CODE REVIEW

**Comment by mgajdos** [comment]
Verified manually. Merging based on #5.

**Comment by HiJon89** [comment]
@mgajdos will this be released soon?

**Comment by jon077** [comment]
Woohoo!  We are excited to see this merge.  Any ETA for release?

**Comment by mgajdos** [comment]
Jersey 1.19 should be released in the next couple of weeks.

**Comment by niesfisch** [comment]
hi, we are currently moving (our big) stack to java 8. jersey 1.18 is currently the foundation. do you already have an idea what "next couple of weeks" means?

cheers
marcel

**Comment by mgajdos** [comment]
The plan is to release Jersey 1.19 at the end of this week (or at the start of the next one).

**Comment by niesfisch** [comment]
@mgajdos: cool, that's good news. thanks for your effort. looking forward to the release. in the meanwhile i try to get everything up und running based on the 1.19-SNAPSHOT version.

cheers
marcel

**Comment by niesfisch** [comment]
i can see that you've checked in version 1.19. how long does it take for the maven repositories to propagate the changes?

**Comment by cowwoc** [comment]
@niesfisch If Michael published a release to Maven Central, it'll take 2 hours to become publicly visible.

**Comment by niesfisch** [comment]
@cowwoc ah that means it hasn't been pushed so far? what is your normal process for this? i thought moving to 1.19 means "push" it to the public maven repos?

**Comment by mgajdos** [comment]
@niesfisch It's already available on Maven Central.

**Pull request merged**
