### PR TITLE
JERSEY-2795: addressing concurrency issues in CopyOnWriteHashMap

### PR DESCRIPTION
**Pull request by djasonpenney**
...implementing CopyOnWriteHashMap to work correctly when used concurrently.  Needed for correct operation of com.netflix.ribbon:ribbon-core:0.3.12

### CODE REVIEW

**Comment by mgajdos** [comment]
Hi @djasonpenney, 
thanks for your contribution.

Before we can review your pull request, we need you to sign Oracle Contributor Agreement.

More information about contributing to Jersey: https://jersey.java.net/scm.html#/Submitting_Patches_and_Contribute_Code…

Regards,
Michal

**Comment by djasonpenney** [comment]
Hi, Michal thank you for your prompt response.  I apologize that I don't
seem to have grasped all of the nuances of your workflow yet.  I also had
trouble yesterday creating a JIRA ticket for this issue.  This seems to
have been resolved today.  I will amend my pull request to include a
reference to the associated ticket.

**Comment by mgajdos** [comment]
I agree that the mentioned problem (NPE) is gone but I'd say there are some unnecessary operations the map does – the former implementation copied the map only when necessary (e.g. map shared between two web-resources and one of the resources tries to put some new value into the map) but current implementation copies the (internal) map every time a modification operation is invoked. This seems too expensive and not necessary.

Also, do not synchronize on `this` object:

    @Override
    public V remove(Object key) {
        synchronized (this) {
            // ...
        }
    }

It may cause a deadlock if a user decides to synchronize some block of code on the same instance (as it's publicly available).

Use dedicated lock object for this instead:

    private final Object lock = new Object();

    @Override
    public V remove(Object key) {
        synchronized (lock) {
            // ...
        }
    }

**Comment by djasonpenney** [comment]
Michal, I agree, a simpler solution is possible here.  I have pushed a new
approach to github.  I hope this one looks better.

**Comment by mgajdos** [comment]
Hi Jason, thanks. This looks better. Once your OCA is confirmed I'll take a second look and your change will be most likely merged.

**Comment by kellyaa** [comment]
I've encountered this same issue as well - I'm very much looking forward to the fix being incorporated.

**Comment by djasonpenney** [comment]
I received notification today that my OCA has been confirmed. Is anything
further required from me?

**Comment by mgajdos** [comment]
Thank you for your contribution Jason.

**Comment by ivan-spread** [comment]
I saw that [Jersey 1.x branch is not under active development anymore](https://java.net/jira/browse/JERSEY-2529?focusedCommentId=389234&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-389234).
Is there any plans/chances to release Jersey 1.20 version, which contains [this fix](https://java.net/jira/browse/JERSEY-2795)?

**Comment by pparth** [comment]
Anyone please answer whether 1.20 is, ever, going to be released with the fixes it has or not? This specific bug raises its ugly head continuously in our production environment.

**Comment by twicksell** [comment]
+1 on waiting for an update regarding release. Our users have come across this recently as well. Any updates would be greatly appreciated.

**Comment by PedroAlvarado** [comment]
@mgajdos Is there anything the community can do to help get 1.20 released?

**Comment by radubutnaru** [comment]
+1, we have hit upon this issue while performing load tests. This has been [reported](https://github.com/spring-cloud/spring-cloud-netflix/issues/749) to the Spring Cloud Netflix project as well.

**Comment by pavelbucek** [comment]
let me see what I can do about this..

**Comment by pavelbucek** [comment]
@PedroAlvarado @radubutnaru  .. FYI: Jersey 1.19.1 has been released and it contains this commit - mentioned components can uptake it.

**Comment by PedroAlvarado** [comment]
@pavelbucek Thank you! I'll socialize the availability of this release in upstream components(netflix-feign).

**Comment by radubutnaru** [comment]
@pavelbucek thanks!

**Pull request merged**
